import turtle
y = turtle.Turtle()
y.hideturtle()
y.fillcolor()
def square(x:int , z:int , c:str):
     y.begin_fill()
     y.color(c)
     y.forward(x)
     y.left(90)
     y.forward(z)
     y.left(90)
     y.forward(x)
     y.left(90)
     y.forward(z)
     y.left(90)
     y.end_fill()
def triangle(x:int, z:int, c:str):
     y.color(c)
     y.begin_fill()
     for i in range(2):
        y.forward(x)
        y.left(z)
     y.end_fill()
square(250,50,"black")
y.right(90)
y.color("white")
y.forward(100)
y.left(90)
square(250,50,"green")
y.left(45)
triangle(107, 90, "red")
turtle.done()